### ISSUE TITLE
大佬，js版本有点小问题找不到luci.mk，还有一个提议。

### ISSUE THREAD

**Issue by dsadaskwq** [sirpdboy/luci-theme-kucat#13]
生成config配置文件的时候没有luci-theme-kucat主题，报错是kucat的Makefile里luci.mk有问题
改成这样就好了，再次生成配置文件出现luci-theme-kucat。
#include ../../luci.mk
include $(TOPDIR)/feeds/luci/luci.mk

还有发现js版手机上 左侧这里不能上下滑动，系统/服务这里东西太多，点不到网络存储和网络这栏，如果左侧能上下滑动就好了，另外大佬辛苦了😁。

**Comment by dsadaskwq** [comment]
[](url)
![IMG_20240107_233731](https://github.com/sirpdboy/luci-theme-kucat/assets/111348232/02cc52e0-51b8-4bf8-8c9d-acaa96392834)

**Comment by sirpdboy** [comment]
好的。问题修复 了。

**Comment by dsadaskwq** [comment]
感谢大佬修复，现在可以在手机上划动侧边栏了
