### ISSUE TITLE
求大佬在Releases更新一个js版的ipk！

### ISSUE THREAD

**Issue by 1256321875** [sirpdboy/luci-theme-kucat#9]
有尝试着按照教程自行编译  但提示找不到文件 过于小白不知道如何解决 希望能在Releases更新一个js版的ipk
![~CK1EAAP}~J}XW XX8T1EOQ](https://github.com/sirpdboy/luci-theme-kucat/assets/115718495/fb3fa4e6-1cb0-48a5-929a-cf99596078a1)

**Comment by sirpdboy** [comment]
已经更新了
